version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev